NETOBSERV-82: Enforcing crd validation to only have one instance per cluster
netobserv/network-observability-operator pull request #15
Opened 2021-11-09 16:02 UTC by OlivierCazade

Using the validation scheme to only accept default as the CRD name, only one instance of the CRD can be created per cluster.

Jira link : https://issues.redhat.com/browse/NETOBSERV-82

2021-11-09 16:06 UTC, mariomac approved these changes
LGTM. Just a minor comment: is `default` the common name for singleton instances in RedHat? E.g. I see that the default network is named `cluster`.

2021-11-10 13:18 UTC, OlivierCazade commented
> LGTM. Just a minor comment: is `default` the common name for singleton instances in RedHat? E.g. I see that the default network is named `cluster`.

Thanks, I could not find official policy but cluster looks like the most used name, I have switched to it.

2021-11-10 13:34 UTC, mariomac approved these changes
LGTM

2021-11-10 13:42 UTC, jotak commented
I get a validation error when applying the CR:

```
error: error validating "./config/samples/flows_v1alpha1_flowcollector.yaml": error validating data: ValidationError(FlowCollector): unknown field "spec" in io.netobserv.flows.v1alpha1.FlowCollector; if you choose to ignore these errors, turn validation off with --validate=false
```

is it just me?

2021-11-10 13:48 UTC, jotak requested changes
looks like all the `openAPIV3Schema` content is replaced with what's in the patch 😬

2021-11-10 14:46 UTC, jotak commented
/approve

2021-11-10 14:50 UTC, jotak commented
/lgtm
/approve

2021-11-10 15:21 UTC, mariomac commented
/approve

2021-11-10 15:23 UTC, merged