Fix regression on deploying latest
netobserv/network-observability-operator pull request #280
Opened 2023-02-28 09:04 UTC by jotak

In https://github.com/netobserv/network-observability-operator/pull/274 the way IMG is used is changed, which broke deploying all latest components

This patch introduces a new "deploy-latest" target to explicitly deploy all components on their `main` branches

2023-02-28 13:16 UTC, msherif1234 requested changes
we need to reflect this new build target in the readme and developement doc files

2023-02-28 13:16 UTC, msherif1234 commented on Makefile
> +deploy-latest: kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
pls fix the comment here to indicate it will deploy all images with `main` tag

2023-02-28 13:32 UTC, msherif1234 commented
so how we can deploy custom build operator image with latest of other components ?
assume u have local changes in the operator and u need to build and push and test with latest of agent/flb and others ?

maybe we can just check if IMG is set to different than default then use it for the operator and use the pinned versions for all others, if not set use latest for all
with just `make deploy` target

2023-02-28 14:49 UTC, memodi commented
@jotak - I tried with `make deploy-latest` target and it still deploys versioned images:
```
(⎈ |bc3721a94cf623d8-elb:netobserv)memodi@memodi-mac:/Users/memodi/workspaces/repos/netobserv/network-observability-operator  (fix-deploy-latest *$)
$ oc describe pod/$NOO | egrep "Image:|IMAGE"
    Image:         quay.io/netobserv/network-observability-operator:main
      --ebpf-agent-image=$(RELATED_IMAGE_EBPF_AGENT)
      --flowlogs-pipeline-image=$(RELATED_IMAGE_FLOWLOGS_PIPELINE)
      --console-plugin-image=$(RELATED_IMAGE_CONSOLE_PLUGIN)
      RELATED_IMAGE_EBPF_AGENT:         quay.io/netobserv/netobserv-ebpf-agent:v0.3.0
      RELATED_IMAGE_FLOWLOGS_PIPELINE:  quay.io/netobserv/flowlogs-pipeline:v0.1.8
      RELATED_IMAGE_CONSOLE_PLUGIN:     quay.io/netobserv/network-observability-console-plugin:v0.1.9
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
```

2023-02-28 15:16 UTC, memodi commented
> so how we can deploy custom build operator image with latest of other components ? assume u have local changes in the operator and u need to build and push and test with latest of agent/flb and others ?

@msherif1234 - I just tried this, deployed the image from PR #263 , I checkout that PR and used IMG that's build on that PR:
```
$ IMG="quay.io/netobserv/network-observability-operator:fea8ce2" make deploy
...
...
$ oc describe pod/$NOO | egrep "Image:|IMAGE"
    Image:         quay.io/netobserv/network-observability-operator:fea8ce2
      --ebpf-agent-image=$(RELATED_IMAGE_EBPF_AGENT)
      --flowlogs-pipeline-image=$(RELATED_IMAGE_FLOWLOGS_PIPELINE)
      --console-plugin-image=$(RELATED_IMAGE_CONSOLE_PLUGIN)
      RELATED_IMAGE_EBPF_AGENT:         quay.io/netobserv/netobserv-ebpf-agent:main
      RELATED_IMAGE_FLOWLOGS_PIPELINE:  quay.io/netobserv/flowlogs-pipeline:main
      RELATED_IMAGE_CONSOLE_PLUGIN:     quay.io/netobserv/network-observability-console-plugin:main
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
```

2023-02-28 15:19 UTC, memodi requested changes
LGTM on the code, it does deploy NOO image tagged with "main" when using "deploy-latest" target. Could we document to set env variable for `SED` for MAC systems because those commands doesn't work when we use other than GNU sed.

2023-02-28 17:24 UTC, jotak commented
Doc updated and should now work with gsed

2023-02-28 17:29 UTC, msherif1234 commented
/lgtm

2023-02-28 17:36 UTC, Amoghrd commented
Verified with `sed` and `gsed` and it deploys the main image for the operator and its components.
/lgtm
Thanks!

2023-02-28 21:25 UTC, memodi commented
/label qe-approved

2023-03-01 07:08 UTC, jotak commented
/approve

2023-03-01 07:12 UTC, merged