enable ebpf metrics by default while keep the knob in case we need to disable
netobserv/network-observability-operator pull request #649
Opened 2024-05-20 14:44 UTC by msherif1234

## Description
enable ebpf metrics by default while still keeping the config in case we need to disable it

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

2024-05-20 14:51 UTC, msherif1234 commented
/ok-to-test

2024-05-20 15:03 UTC, memodi reviewed
/label qe-approved (based on code inspection)

2024-05-20 15:05 UTC, memodi commented
/label qe-approved

2024-05-20 15:33 UTC, msherif1234 commented
![image](https://github.com/netobserv/network-observability-operator/assets/12748167/6802fa3b-3d95-4a6c-ad6d-29a74d004688)

2024-05-21 10:12 UTC, msherif1234 commented
/approve

2024-05-21 10:12 UTC, jotak requested changes
Sorry I approved too fast
You need to update `IsEBPFMetricsEnabled` in helper package

2024-05-21 10:13 UTC, msherif1234 commented
/hold

2024-05-21 10:14 UTC, jotak commented
@msherif1234 the default was not controlled via openapi/kubebuilder, but in code instead. Like in other places, this is in order to keep control on what we set as defaults, even for users who are upgrading and who might already have a FlowCollector installed.

2024-05-21 10:35 UTC, msherif1234 commented
/hold cancel

2024-05-21 11:03 UTC, msherif1234 commented on apis/flowcollector/v1beta1/flowcollector_types.go
> +	//+kubebuilder:default:=true
removed it

2024-05-21 14:31 UTC, jotak approved these changes

2024-05-21 14:34 UTC, merged