NETOBSERV-1672: add cluster & zone to predefined metrics
netobserv/network-observability-operator pull request #665
Opened 2024-05-30 16:22 UTC by jotak

## Description

Add cluster & zone to predefined metrics
They're only added when those features are enabled.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

2024-06-03 09:13 UTC, jpinsonneau approved these changes

2024-06-03 20:28 UTC, memodi requested changes
@jotak - I can see the views for Zone, however cluster aggregation is still missing. When Prom. as datasource is selected (when Loki is enabled) I get error as:
```
Unable to get topology
Can't build query: this request could not be performed with Prometheus metrics, as they are missing some of the required labels. Try using different filters and/or aggregations. For example, try removing these dependencies from your query: K8S_ClusterName. Alternatively, you may also install and enable Loki
```
Cluster option is not enabled when loki is disabled and Prom. is enabled.

2024-06-04 07:42 UTC, jotak commented
@memodi did you use the latest generated image, not the first one? ie. a3ff45b and not c20ce8c. Because I had this same problem at first and I (should have) fixed it in the second build

2024-06-04 13:50 UTC, memodi commented
> @memodi did you use the latest generated image, not the first one? ie. [a3ff45b](https://github.com/netobserv/network-observability-operator/commit/a3ff45bf4ffb8a104c17b6b3c65624d4518166b1) and not [c20ce8c](https://github.com/netobserv/network-observability-operator/commit/c20ce8cb1ca461af98da859b07b9690312988aa6). Because I had this same problem at first and I (should have) fixed it in the second build

ah, yes, I had used a3ff45b, I'll try with with c20ce8c

2024-06-04 14:55 UTC, memodi commented
thanks @jotak , [a3ff45b](https://github.com/netobserv/network-observability-operator/commit/a3ff45bf4ffb8a104c17b6b3c65624d4518166b1) works.

/label qe-approved

2024-06-04 15:24 UTC, merged